"""Pluggable position congruence: the second semantic parameter (the equality on positions).

The readout folds a position re-entered during its own computation (``_readout._read``). WHICH
positions count as "the same" is a parameter, a *position congruence*. Syntactic-identity
interning (a pointer test) is the FINEST instance and the default; coarser sound congruences
fold more, so a term whose finest-congruence position set is infinite can still fold.

A congruence is SOUND when it is contained in tree equality (it never identifies positions with
different trees). Stated over the full signature (the meaningless ``bottom`` and variable indices
included), the congruence law is the soundness law read coinductively, so a well-formed
congruence is sound by construction; see ``first-order/first-order.tex`` (``def:congruence``).

Two instances live here:
- ``IdentityCongruence``: the finest instance, ``key = id(node)``, the default. Reproduces the
  pure-interning behaviour exactly.
- ``EGraphCongruence``: a union-find with congruence closure. The caller asserts sound merges
  (tree-equal positions) and the closure propagates them through ``App``/``Lam`` parents. This is
  the inductive (least-fixpoint) family of congruences: it folds whatever is generated by
  finitely many tree-equal pairs. It cannot, by construction, fold a congruence that is not
  finitely generated (a purely coinductive identity); that is the job of a tree-preserving
  canonicalising map (see ``_deadsubterm``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Final, Hashable, Protocol, final, runtime_checkable

from first_order_lambda._ast import App, Lam, Node, ShapeBottom, Var
from first_order_lambda._shape import AppShape, LamShape, VarShape, shape_of


@runtime_checkable
class Congruence(Protocol):
    """Maps a position to the key the readout folds on. Equal keys fold together."""

    def key(self, node: Node) -> Hashable: ...


@final
@dataclass(kw_only=True, slots=True, frozen=True, weakref_slot=True)
class IdentityCongruence:
    """The finest instance: syntactic (de Bruijn) identity, a pointer test. The default.

    ``id(node)`` is exact because the AST is interned (``_ast.make_*``), so structurally equal
    positions are already one object. This congruence therefore folds exactly the cycles the
    pure-interning readout folds.
    """

    def key(self, node: Node) -> Hashable:
        return id(node)


IDENTITY_CONGRUENCE: Final[IdentityCongruence] = IdentityCongruence()


def _signature(node: Node, find: Callable[[int], int]) -> tuple[object, ...]:
    """The congruence signature of ``node``: its constructor over its children's class reps.

    Two registered nodes are congruent (must share a class) exactly when their signatures
    coincide. ``Var`` carries its index, so distinct variables never merge; ``Lam``/``App`` key
    on the class reps of their children, so a merge of children propagates to the parents.
    """
    match node:
        case Var(index=index):
            return ("Var", index)
        case Lam(body=body):
            return ("Lam", find(id(body)))
        case App(function=function, argument=argument):
            return ("App", find(id(function)), find(id(argument)))
        case _:
            raise TypeError(f"Unknown node {node!r}")


@final
@dataclass(kw_only=True, slots=True, weakref_slot=True, eq=False)
class EGraphCongruence:
    """A union-find over positions with congruence closure, the inductive congruence family.

    ``merge(a, b)`` asserts ``a`` and ``b`` denote the same tree (the SOUNDNESS obligation is on
    the caller; the merge is in tree equality by assumption). Closure then merges any two
    registered ``App``/``Lam`` nodes whose children have become class-equal. ``key`` returns the
    class representative, so the readout folds congruent positions.

    With no merges asserted this is exactly ``IdentityCongruence`` (every node is its own class),
    so it is behaviour-preserving by default.
    """

    _parent: Final[dict[int, int]] = field(default_factory=dict)
    _registry: Final[dict[int, Node]] = field(default_factory=dict)

    def _register(self, node: Node) -> None:
        node_id = id(node)
        if node_id in self._registry:
            return
        self._registry[node_id] = node
        self._parent.setdefault(node_id, node_id)
        match node:
            case Var():
                pass
            case Lam(body=body):
                self._register(body)
            case App(function=function, argument=argument):
                self._register(function)
                self._register(argument)
            case _:
                raise TypeError(f"Unknown node {node!r}")

    def _find(self, node_id: int) -> int:
        root = node_id
        while self._parent[root] != root:
            root = self._parent[root]
        # Path compression.
        while self._parent[node_id] != root:
            self._parent[node_id], node_id = root, self._parent[node_id]
        return root

    def _union(self, left_id: int, right_id: int) -> bool:
        left_root, right_root = self._find(left_id), self._find(right_id)
        if left_root == right_root:
            return False
        self._parent[right_root] = left_root
        return True

    def _close(self) -> None:
        """Propagate congruence to a fixpoint: equal signatures collapse to one class."""
        changed = True
        while changed:
            changed = False
            by_signature: dict[tuple[object, ...], int] = {}
            for node_id, node in self._registry.items():
                signature = _signature(node, self._find)
                representative = by_signature.get(signature)
                if representative is None:
                    by_signature[signature] = node_id
                elif self._union(representative, node_id):
                    changed = True

    def merge(self, left: Node, right: Node) -> None:
        """Assert ``left`` and ``right`` denote the same tree, then close under congruence.

        Soundness obligation: ``left`` and ``right`` MUST be tree-equal. The merge is taken to be
        contained in tree equality; an unsound merge silently corrupts the readout.
        """
        self._register(left)
        self._register(right)
        self._union(id(left), id(right))
        self._close()

    def key(self, node: Node) -> Hashable:
        node_id = id(node)
        if node_id not in self._parent:
            # The readout creates positions lazily, so register on first sight and re-close:
            # a newly seen parent of already-merged children joins their class by congruence.
            self._register(node)
            self._close()
        return self._find(node_id)


@final
@dataclass(kw_only=True, slots=True, frozen=True, weakref_slot=True)
class PositionEGraphCongruence:
    """The faithful ``def:congruence``: a congruence over the DEMANDED descent, not the syntactic
    structure. The key is the rational shape tree of a position, so two positions fold exactly
    when they are bisimilar under the shape relation ``Sh``.

    Unlike ``EGraphCongruence`` (which closes over the syntactic constructors and folds only what
    finitely many asserted tree-equal pairs generate), this auto-folds any two positions whose
    onward shapes agree, with no asserted merges: a redex and its reduct, or two encodings with the
    same rational tree, collapse on sight. It is sound by construction (equal shape trees are equal
    trees, Part 3b).

    It folds exactly the RATIONAL fragment: the key is computed by descending the shape with cycle
    detection, so a position whose shape graph is finite (a guarded cycle interns back) gets a
    finite key. A position whose shape graph is infinitely presented (distinct positions all the
    way down, as the ``Y F 0`` witness, where a dead argument keeps every tail position distinct)
    has no finite key: the descent never re-enters a position, so the key computation diverges,
    exactly as the readout itself does. Bisimulation cannot finitize an infinite presentation; that
    needs the dead argument recognised and erased, which is a separate tree-preserving map, not a
    congruence closure.
    """

    def key(self, node: Node) -> Hashable:
        return _shape_fingerprint(node, {})


def _shape_fingerprint(node: Node, on_path: dict[int, int]) -> Hashable:
    """The rational shape tree of ``node`` as a hashable value, cycles closed by a relative
    back-reference. Equal fingerprints mean bisimilar (tree-equal) positions."""
    node_id = id(node)
    back_depth = on_path.get(node_id)
    if back_depth is not None:
        # A guarded cycle: point back to the ancestor by its relative depth, so the fingerprint
        # is the finite rational tree rather than its infinite unfolding.
        return ("back", len(on_path) - back_depth)
    on_path[node_id] = len(on_path)
    try:
        shape = shape_of(node)
        match shape:
            case ShapeBottom.BOTTOM:
                return ("bottom",)
            case VarShape(index=index):
                return ("var", index)
            case LamShape(body=body):
                return ("lam", _shape_fingerprint(body, on_path))
            case AppShape(function=function, argument=argument):
                return (
                    "app",
                    _shape_fingerprint(function, on_path),
                    _shape_fingerprint(argument, on_path),
                )
            case _:
                raise TypeError(f"Unknown shape {shape!r}")
    finally:
        del on_path[node_id]


_DEAD_ARGUMENT: Final[tuple[str]] = ("dead-argument",)
"""The canonical placeholder a dead argument erases to, so two positions that differ only in a
dead slot get the same key."""


@runtime_checkable
class DeadArgumentRule(Protocol):
    """A sound predicate: ``is_dead(application)`` is ``True`` only when the application's argument
    occupies a dead slot, so erasing it preserves the tree. The rules form a library; the caller
    enables a subset (``DeadSubtermCongruence(rules=...)``). Each rule's soundness is its own
    obligation, established by a decidable, conservative check (never demanded ⊆ tree equality)."""

    def is_dead(self, application: App) -> bool: ...


def _applies_recursion(term: Node, recursion_node: Node) -> bool:
    """Whether ``term`` is ``recursion_node`` applied to one or more arguments, i.e.
    ``recursion_node`` sits on the function spine of ``term``. Stops at ``recursion_node`` rather
    than peeling through its own structure (the recursion is an unfolded self-application, itself
    an ``App``)."""
    while isinstance(term, App):
        if term.function is recursion_node:
            return True
        term = term.function
    return False


def _is_free(term: Node, index: int) -> bool:
    """Whether de Bruijn ``index`` occurs free in ``term``."""
    if term.loose_bound <= index:
        return False
    match term:
        case Var(index=occurrence):
            return occurrence == index
        case Lam(body=body):
            return _is_free(body, index + 1)
        case App(function=function, argument=argument):
            return _is_free(function, index) or _is_free(argument, index)
        case _:
            raise TypeError(f"Unknown node {term!r}")


@final
@dataclass(kw_only=True, slots=True, frozen=True, weakref_slot=True)
class UnusedParameterRule:
    """The argument of ``f a`` is dead when ``f``'s weak-head normal form binds a parameter that
    is not used in its body: the value of ``a`` cannot reach any demanded position. Always sound
    (beta erases it regardless of ``a``), decidable, and the simplest library rule."""

    def is_dead(self, application: App) -> bool:
        shape = shape_of(application.function)
        if not isinstance(shape, LamShape):
            return False
        return not _is_free(shape.body, 0)


def _parameter_dead(term: Node, *, dead_index: int, recursion_node: Node) -> bool:
    """Whether de Bruijn ``dead_index`` occurs in ``term`` only inside argument positions of
    applications whose spine head is ``recursion_node`` (the recursion, identified by object
    identity since it is a closed interned position). Under that condition the parameter is never
    demanded: the recursion's output is independent of it, coinductively, so erasing it preserves
    the tree. A finite syntactic test of a greatest-fixpoint property."""
    if term.loose_bound <= dead_index:
        return True
    match term:
        case Var(index=index):
            return index != dead_index
        case Lam(body=body):
            # ``recursion_node`` is closed, so it appears as the same object under the binder.
            return _parameter_dead(
                body, dead_index=dead_index + 1, recursion_node=recursion_node
            )
        case App(function=function, argument=argument):
            if _applies_recursion(term, recursion_node):
                # term = (recursion arg1 ... argk): every argument sits in a dead slot, so
                # dead_index is not demanded here.
                return True
            return _parameter_dead(
                function, dead_index=dead_index, recursion_node=recursion_node
            ) and _parameter_dead(
                argument, dead_index=dead_index, recursion_node=recursion_node
            )
        case _:
            raise TypeError(f"Unknown node {term!r}")


@final
@dataclass(kw_only=True, slots=True, frozen=True, weakref_slot=True)
class RecursionArgumentRule:
    """The argument of ``g a`` is dead when ``g`` weak-head-normalizes to ``lambda n. body`` that
    threads ``n`` only into argument positions of the recursion ``g`` itself (never into a demanded
    head). This is the witness pattern: a constant-headed recursion carrying an index it never
    inspects. Sound (the parameter is never demanded, so the tree is independent of ``a``) and
    decidable.

    The recursion is detected by the WEAK-HEAD SHAPE of ``g`` and the object identity of ``g`` as
    its own self-reference, not by a syntactic ``Y``: after reduction the fixpoint combinator is
    gone (the self-reference is the unfolded self-application), so a syntactic match would miss the
    reduced tail positions the readout actually reaches."""

    def is_dead(self, application: App) -> bool:
        recursion = application.function
        shape = shape_of(recursion)
        if not isinstance(shape, LamShape):
            return False
        # ``shape.body`` is the body of ``lambda n. ...``, so the threaded parameter is de Bruijn 0
        # and the recursion's self-reference inside it is ``recursion`` itself.
        return _parameter_dead(shape.body, dead_index=0, recursion_node=recursion)


@final
@dataclass(kw_only=True, slots=True, weakref_slot=True, eq=False)
class DeadSubtermCongruence:
    """Equality up to dead subterms (Method B): the key is the syntax with every dead-argument
    slot erased to a canonical placeholder. A tree-preserving canonical map, so two positions that
    differ only in dead subterms fold together; the ``Y F 0`` witness folds because its tail
    positions differ only in a dead index.

    The fold is decided by a LIBRARY of sound ``rules``; the caller enables a subset. This sits
    where neither e-graph reaches: it is not a congruence closure (it does not fold redex with
    reduct) but a canonicalising erasure, so it captures the coinductive identity the witness
    needs while staying a finite, terminating syntactic pass.

    The canonical form of each node is cached by ``id(node)`` (safe because nodes are interned),
    so repeated ``key()`` calls are ``O(1)`` after the first traversal.
    """

    rules: Final[tuple[DeadArgumentRule, ...]]
    _cache: Final[dict[int, Hashable]] = field(default_factory=dict)

    def key(self, node: Node) -> Hashable:
        node_id = id(node)
        cached = self._cache.get(node_id)
        if cached is not None:
            return cached
        result = self._canonical(node)
        self._cache[node_id] = result
        return result

    def _canonical(self, node: Node) -> Hashable:
        node_id = id(node)
        cached = self._cache.get(node_id)
        if cached is not None:
            return cached
        match node:
            case Var(index=index):
                result: Hashable = ("var", index)
            case Lam(body=body):
                result = ("lam", self._canonical(body))
            case App(function=function, argument=argument):
                if any(rule.is_dead(node) for rule in self.rules):
                    result = ("app", self._canonical(function), _DEAD_ARGUMENT)
                else:
                    result = ("app", self._canonical(function), self._canonical(argument))
            case _:
                raise TypeError(f"Unknown node {node!r}")
        self._cache[node_id] = result
        return result
