# Generated by first-order/generate_examples.py from the COMPILE lambda term. Do not edit.
# This is the pure-lambda compiler COMPILE compiled to Python by the bootstrap compiler
# (compile_to_source(build(COMPILE))): a Python function from a host-encoded quoted source term
# to a host-encoded quoted Python expression (see _compiler.compile_with for the calling
# convention). Regenerate with: python3 first-order/generate_examples.py

compiled_compiler = (lambda v0: (lambda v1: v0(lambda v2: v1(v1)(v2)))(lambda v1: v0(lambda v2: v1(v1)(v2))))(lambda v0: lambda v1: lambda v2: v2(lambda v3: lambda v4: lambda v5: lambda v6: v4((lambda v7: lambda v8: v8(lambda v9: lambda v10: lambda v11: v9(lambda v12: lambda v13: v13(v12(v10)))(lambda v12: v11)(lambda v12: v12))(v7))(v1)((lambda v7: lambda v8: lambda v9: v8(v7(v8)(v9)))(v3))))(lambda v3: lambda v4: lambda v5: lambda v6: v5(v1)(v0((lambda v7: lambda v8: lambda v9: v8(v7(v8)(v9)))(v1))(v3)))(lambda v3: lambda v4: lambda v5: lambda v6: lambda v7: v7(v0(v1)(v3))(v0(v1)(v4))))
