"""Build the generated artifacts: the LaTeX appendix fragment and the self-compiled compiler module.

These are pure, deterministic string builders. ``first-order/generate_examples.py`` writes them to
disk, and tests assert the committed files match these builders, so the artifacts cannot drift from
the compiler. Every example runs the real specializer or the real compiler: a whole-term example is
``specialize`` of the term (the certified target and its emitted Python), the cyclic example is a
compiled call-by-value island spliced into an interpreted shell, and the flagship is the call-by-value
islands the specializer finds inside the compiler itself. The displayed lambda is ``term_to_latex`` of
the term (readable names), or a named-combinator form for the composite terms whose full expansion
would be unreadable.
"""

from __future__ import annotations

from first_order_lambda._compiler import COMPILE, Runtime, compile_interpreted, compile_to_source
from first_order_lambda._dsl import Builder, app, build
from first_order_lambda._latex import term_to_latex
from first_order_lambda._prelude import (
    IDENTITY,
    IS_ZERO,
    KESTREL,
    MULT,
    PLUS,
    SCOTT_CONS,
    SELF_APPLY,
    SUCC,
    Y,
    church,
)
from first_order_lambda._specialize import call_by_value_islands, specialize

_LATEX_HEADER = (
    "% Generated by first-order/generate_examples.py from the first_order_lambda compiler.\n"
    "% Do not edit; regenerate with: python3 first-order/generate_examples.py\n"
)

_PYTHON_HEADER = (
    "# Generated by first-order/generate_examples.py from the COMPILE lambda term. Do not edit.\n"
    "# This is the compiler COMPILE compiled to Python in specialized mode (compile_specialized).\n"
    "# COMPILE is untypable (its Z fixpoint self-applies), so it has no whole-graph by-value\n"
    "# certificate and compiles to interpret-headed Python: the COMPILE node, reconstructed with the\n"
    "# interning constructors and handed back to the interpreter. Run it with _compiler.\n"
    "# compile_with_interpreted. Regenerate with: python3 first-order/generate_examples.py\n"
)

# Readable target labels for the example headings (the enum name has underscores).
_RUNTIME_LABEL = {
    Runtime.CALL_BY_VALUE: "call-by-value",
    Runtime.CALL_BY_NAME: "call-by-name",
    Runtime.CALL_BY_NEED: "call-by-need",
    Runtime.INTERPRET: "interpret",
}

# Whole-term specialized examples: the specializer certifies one target for the whole closed term.
# A simply-typable term is one strongly-normalizing call-by-value island; an untypable but normalizing
# term (self-application reuses its bound variable, so the value is shared) certifies call-by-need.
# Each pairs (title, builder, latex): latex is None to auto-render with readable names.
_WHOLE_TERM_EXAMPLES: tuple[tuple[str, Builder, str | None], ...] = (
    ("Identity", IDENTITY, None),
    ("The constant combinator $K$", KESTREL, None),
    ("Church numeral $2$", church(2), None),
    ("Successor", SUCC, None),
    ("Addition", PLUS, None),
    ("Multiplication", MULT, None),
    ("Zero test", IS_ZERO, None),
    ("Self-application", SELF_APPLY, None),
)

# The cyclic stream of nines: a fold-requiring shell whose closed element is a compiled island.
_CYCLIC_NINES: Builder = app(Y, app(SCOTT_CONS, app(app(MULT, church(3)), church(3))))


def _listing(source: str) -> str:
    return "\\begin{lstlisting}\n" + source + "\n\\end{lstlisting}\n"


def _whole_term_block(title: str, builder: Builder, latex: str | None) -> str:
    node = build(builder)
    runtime, source = specialize(node)
    assert source is not None, "the whole-term examples are all certified to a compiled target"
    rendered = latex if latex is not None else term_to_latex(node)
    note = f"~\\textnormal{{(specialized to {_RUNTIME_LABEL[runtime]})}}"
    heading = f"\\medskip\\noindent\\textbf{{{title}.}}{note}\\quad ${rendered}$\n"
    return heading + _listing(source)


def _cyclic_island_block() -> str:
    """The runnable local specialization: a call-by-value data island in an interpreted cyclic shell."""
    whole = build(_CYCLIC_NINES)
    runtime, _ = specialize(whole)
    assert runtime is Runtime.INTERPRET, "a fold-requiring cyclic term stays interpreted as a whole"
    element = build(app(app(MULT, church(3)), church(3)))
    heading = (
        "\\medskip\\noindent\\textbf{Local specialization in a cyclic term.}"
        "~\\textnormal{(specialized to interpret)}\\quad $Y\\,(\\mathtt{cons}\\,(3 \\times 3))$\n"
    )
    note = (
        "The cyclic stream is fold-requiring, so the whole term stays interpreted; its closed element "
        "$3 \\times 3$ is simply typable, hence a call-by-value island compiled to strict Python:\n"
    )
    result = (
        "The island runs and the interpreter folds around it, so the result is the same finite cyclic "
        "behaviour as pure interpretation, the stream $\\mathtt{cons}\\,9\\,(\\mathtt{cons}\\,9\\,\\cdots)$ "
        "folded to a single cyclic node.\n"
    )
    return heading + note + _listing(compile_to_source(element, Runtime.CALL_BY_VALUE)) + result


def _compiler_islands_block() -> str:
    """The flagship: the call-by-value islands the specializer finds inside the compiler itself."""
    islands = call_by_value_islands(build(COMPILE))
    heading = (
        "\\medskip\\noindent\\textbf{The compiler, specialized: finding call-by-value islands.}\\quad "
        "The compiler is untypable as a whole, since its fixpoint combinator $Z$ self-applies, so it "
        f"stays interpreted; the specializer finds its {len(islands)} maximal closed simply-typable "
        "sub-terms, each a strongly-normalizing combinator compiled to a strict call-by-value island, "
        "while the recursive skeleton is left to the interpreter:\n"
    )
    parts = [
        f"\\smallskip\\noindent ${term_to_latex(island)}$\n"
        + _listing(compile_to_source(island, Runtime.CALL_BY_VALUE))
        for island in islands
    ]
    return heading + "\n".join(parts)


def compiler_examples_fragment() -> str:
    """The LaTeX fragment: the specializer's output per term, the islands it finds, and self-hosting."""
    whole_terms = [_whole_term_block(title, builder, latex) for title, builder, latex in _WHOLE_TERM_EXAMPLES]
    bootstrap = (
        "\\medskip\\noindent\\textbf{The compiler itself, compiled in specialized mode (self-hosting).}\\quad "
        "The compiler has no whole-graph by-value certificate, so it compiles to interpret-headed Python: "
        "the compiler reconstructed as an interpreter term and handed back to the interpreter. This is the "
        "self-compiled compiler committed as the generated module \\texttt{\\_generated\\_compiler.py}; run "
        "by the interpreter on a quoted program, it emits the same Python as the in-process compiler:\n"
        + _listing(compile_interpreted(build(COMPILE)))
    )
    return (
        _LATEX_HEADER
        + "\n"
        + "\n".join(whole_terms)
        + "\n"
        + _cyclic_island_block()
        + "\n"
        + _compiler_islands_block()
        + "\n"
        + bootstrap
    )


def generated_compiler_module_text() -> str:
    """The self-compiled compiler: COMPILE compiled in specialized mode (interpret-headed) to its node."""
    return (
        _PYTHON_HEADER
        + "\nfrom first_order_lambda._ast import make_app, make_lam, make_var\n"
        + "from first_order_lambda._compiler import interpret\n\n"
        + "compiled_compiler = "
        + compile_interpreted(build(COMPILE))
        + "\n"
    )
