"""Build the generated artifacts: the LaTeX appendix fragment and the self-compiled compiler module.

These are pure, deterministic string builders. ``first-order/generate_examples.py`` writes them to
disk, and tests assert the committed files match these builders, so the artifacts cannot drift from
the compiler. Every example's Python is the real ``compile_to_source`` output, and every displayed
lambda is ``term_to_latex`` of the same term, named to match.
"""

from __future__ import annotations

from first_order_lambda._compiler import COMPILE, Runtime, compile_to_source
from first_order_lambda._dsl import Builder, build
from first_order_lambda._latex import term_to_latex
from first_order_lambda._prelude import (
    IDENTITY,
    IS_ZERO,
    KESTREL,
    MULT,
    PLUS,
    SUCC,
    church,
)

_LATEX_HEADER = (
    "% Generated by first-order/generate_examples.py from the first_order_lambda compiler.\n"
    "% Do not edit; regenerate with: python3 first-order/generate_examples.py\n"
)

_PYTHON_HEADER = (
    "# Generated by first-order/generate_examples.py from the COMPILE lambda term. Do not edit.\n"
    "# This is the pure-lambda compiler COMPILE compiled to Python by the bootstrap compiler\n"
    "# (compile_to_source(build(COMPILE))): a Python function from a host-encoded quoted source term\n"
    "# to a host-encoded quoted Python expression (see _compiler.compile_with for the calling\n"
    "# convention). Regenerate with: python3 first-order/generate_examples.py\n"
)

# (title, builder, runtime): each compiles to readable Python; one LAZY entry shows the thunk target.
_EXAMPLES: tuple[tuple[str, Builder, Runtime], ...] = (
    ("Identity", IDENTITY, Runtime.EAGER),
    ("The constant combinator $K$", KESTREL, Runtime.EAGER),
    ("Church numeral $0$", church(0), Runtime.EAGER),
    ("Church numeral $2$", church(2), Runtime.EAGER),
    ("Successor", SUCC, Runtime.EAGER),
    ("Addition", PLUS, Runtime.EAGER),
    ("Multiplication", MULT, Runtime.EAGER),
    ("Zero test", IS_ZERO, Runtime.EAGER),
    ("Identity, call-by-name target", IDENTITY, Runtime.LAZY),
)


def _listing(source: str) -> str:
    return "\\begin{lstlisting}\n" + source + "\n\\end{lstlisting}\n"


def _example_block(title: str, builder: Builder, runtime: Runtime) -> str:
    node = build(builder)
    note = "" if runtime is Runtime.EAGER else f"~\\textnormal{{({runtime.name.lower()} runtime)}}"
    heading = f"\\medskip\\noindent\\textbf{{{title}.}}{note}\\quad $" + term_to_latex(node) + "$\n"
    return heading + _listing(compile_to_source(node, runtime))


def compiler_examples_fragment() -> str:
    """The LaTeX fragment: a one-to-one comparison of each source lambda and the Python emitted."""
    blocks = [_example_block(title, builder, runtime) for title, builder, runtime in _EXAMPLES]
    bootstrap = (
        "\\medskip\\noindent\\textbf{The compiler itself, compiled to Python (self-hosting).}\\quad "
        "The compiler $\\mathtt{compile}$ above, compiled by itself, is the Python function committed "
        "as the generated module \\texttt{\\_generated\\_compiler.py}:\n"
        + _listing(compile_to_source(build(COMPILE)))
    )
    return _LATEX_HEADER + "\n" + "\n".join(blocks) + "\n" + bootstrap


def generated_compiler_module_text() -> str:
    """The Python source of the self-compiled compiler: COMPILE compiled to a Python function."""
    return _PYTHON_HEADER + "\ncompiled_compiler = " + compile_to_source(build(COMPILE)) + "\n"
