# Generated by first-order/generate_examples.py from the COMPILE lambda term. Do not edit.
# This is the compiler COMPILE compiled to Python in specialized mode (compile_specialized).
# COMPILE is untypable (its Z fixpoint self-applies), so it has no whole-graph by-value
# certificate and compiles to interpret-headed Python: the COMPILE node, reconstructed with the
# interning constructors and handed back to the interpreter. Run it with _compiler.
# compile_with_interpreted. Regenerate with: python3 first-order/generate_examples.py

from first_order_lambda._ast import make_app, make_lam, make_var
from first_order_lambda._compiler import (
    church_function_island,
    church_island,
    identity_island,
    interpret,
)

compiled_compiler = interpret(make_lam(make_app(make_lam(make_app(make_lam(make_app(make_var(1), make_lam(make_app(make_app(make_var(1), make_var(1)), make_var(0))))), make_lam(make_app(make_var(1), make_lam(make_app(make_app(make_var(1), make_var(1)), make_var(0))))))), make_lam(make_lam(make_lam(make_app(make_app(make_app(make_var(0), make_lam(make_app(make_app(make_app(make_var(4), make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_var(1), make_var(5))))))))), identity_island()), make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_var(4), make_app(make_app(make_lam(make_lam(make_app(make_app(make_var(0), make_lam(make_lam(make_lam(make_app(make_app(make_app(make_var(2), make_lam(make_lam(make_app(make_var(0), make_app(make_var(1), make_var(3)))))), make_lam(make_var(1))), identity_island()))))), make_var(1)))), make_var(7)), make_app(make_lam(make_lam(make_lam(make_app(make_var(1), make_app(make_app(make_var(2), make_var(1)), make_var(0)))))), make_var(5)))))))))))), make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_app(make_var(3), make_var(7)), make_app(make_app(make_var(8), make_app(make_lam(make_lam(make_lam(make_app(make_var(1), make_app(make_app(make_var(2), make_var(1)), make_var(0)))))), make_var(7))), make_var(5)))))))))), make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_app(make_var(2), make_app(make_app(make_app(make_var(10), make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_var(1), make_var(5))))))))), identity_island()), make_app(make_app(make_var(9), make_var(8)), make_var(6)))), make_app(make_app(make_app(make_var(10), make_lam(make_lam(make_lam(make_lam(make_lam(make_lam(make_app(make_var(0), make_var(5))))))))), identity_island()), make_app(make_app(make_var(9), make_var(8)), make_var(5))))))))))))))))))
