#!/usr/bin/env python3
"""Write the generated artifacts: the compiler-example LaTeX fragment.

Run from the repo root with the package on the path, for example:

    PYTHONPATH=packages/first-order-lambda/src:packages/fixpoints/src \\
        python3 first-order/generate_examples.py

The output is committed; the paper build stays pure LaTeX. A test asserts the committed file matches
this builder, so regenerating after a compiler change is mandatory (and idempotent otherwise). The
self-compiled compilers are the staged compilers under first-order/generated/stages/, regenerated by
first-order/benchmark_self_compilation.py.
"""

from __future__ import annotations

from pathlib import Path

from first_order_lambda._generate import compiler_examples_fragment

_REPO_ROOT = Path(__file__).resolve().parent.parent

_LATEX_OUTPUT = _REPO_ROOT / "first-order" / "generated" / "compiler-examples.tex"


def main() -> None:
    _LATEX_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _LATEX_OUTPUT.write_text(compiler_examples_fragment())
    print(f"wrote {_LATEX_OUTPUT}")


if __name__ == "__main__":
    main()
