"""The Scott-encoded Python AST, generated by reflection on ``ast``, round-trips real Python.

The compiler's target is a Python AST represented in the pure lambda-calculus by Scott encoding.
``encode`` reflects a real ``ast`` node into a Scott value; ``decode`` runs that value in the
interpreter and rebuilds the ``ast`` node generically with ``cls(*fields)``. A faithful encoding
means ``decode . encode`` is the identity on the AST, so the unparsed source round-trips, and the
decoded program runs.
"""

from __future__ import annotations

import ast

from first_order_lambda._dsl import build
from first_order_lambda._pyast import encode, roundtrip, to_python_source


def test_expressions_round_trip_faithfully() -> None:
    for source in (
        "v0 + 1",
        "lambda v0: v0 + 1",
        "(lambda v0: v0 + 1)(2)",
        "lambda x: lambda y: x + y",
        "f(1 + 2, x)",
        "x < 3",
    ):
        assert roundtrip(source, mode="eval") == ast.unparse(ast.parse(source, mode="eval"))


def test_module_with_a_loop_round_trips_and_runs() -> None:
    source = (
        "def f(n):\n"
        "    total = 0\n"
        "    while total < n:\n"
        "        total = total + 1\n"
        "    return total\n"
    )
    decoded = roundtrip(source, mode="exec")
    assert decoded == ast.unparse(ast.parse(source))
    namespace: dict = {}
    exec(decoded, namespace)
    assert namespace["f"](5) == 5


def test_scott_ast_decodes_and_executes() -> None:
    node = build(encode(ast.parse("(lambda v0: v0 + 1)(41)", mode="eval")))
    assert eval(to_python_source(node)) == 42
