"""Build the generated artifacts: the LaTeX appendix fragment and the self-compiled compiler module.

These are pure, deterministic string builders. ``co_lambda._generate_examples`` writes them to
disk, and tests assert the committed files match these builders, so the artifacts cannot drift from
the compiler. Every example runs the real specializer or the real compiler: a whole-term example is
``specialize`` of the term (the certified target and its emitted Python), the cyclic example is a
compiled call-by-value island spliced into an interpreted shell, and the flagship is the call-by-value
islands the specializer finds inside the compiler itself. The displayed lambda is ``term_to_latex`` of
the term (readable names), or a named-combinator form for the composite terms whose full expansion
would be unreadable.
"""

from __future__ import annotations

from co_lambda._codec import church
from co_lambda._compiler import CODEGEN
from co_lambda._dsl import Builder, app, build
from co_lambda._latex import term_to_latex
from co_lambda._prelude import (
    FACTORIAL,
    IDENTITY,
    IS_ZERO,
    KESTREL,
    MULT,
    PLUS,
    SCOTT_CONS,
    SELF_APPLY,
    SUCC,
    Y,
)
from co_lambda._specialize import Runtime, call_by_value_islands, codegen, compile, specialize

_LATEX_HEADER = (
    "% Generated by co_lambda._generate_examples from the co_lambda compiler.\n"
    "% Do not edit; regenerate with: python -m co_lambda._generate_examples\n"
)

# Readable target labels for the example headings (the enum name has underscores).
_RUNTIME_LABEL = {
    Runtime.CALL_BY_VALUE: "call-by-value",
    Runtime.CALL_BY_NAME: "call-by-name",
    Runtime.CALL_BY_NEED: "call-by-need",
    Runtime.INTERPRET: "interpret",
}

# Whole-term specialized examples: the specializer certifies one target for the whole closed term.
# A simply-typable term is one strongly-normalizing call-by-value island; an untypable but normalizing
# term (self-application reuses its bound variable, so the value is shared) certifies call-by-need.
# Each pairs (title, builder, latex): latex is None to auto-render with readable names.
_WHOLE_TERM_EXAMPLES: tuple[tuple[str, Builder, str | None], ...] = (
    ("Identity", IDENTITY, None),
    ("The constant combinator $K$", KESTREL, None),
    ("Church numeral $2$", church(2), None),
    ("Successor", SUCC, None),
    ("Addition", PLUS, None),
    ("Multiplication", MULT, None),
    ("Zero test", IS_ZERO, None),
    ("Self-application", SELF_APPLY, None),
)

# The cyclic stream of nines: a fold-requiring shell whose closed element is a compiled island.
_CYCLIC_NINES: Builder = app(Y, app(SCOTT_CONS, app(app(MULT, church(3)), church(3))))


def _listing(source: str) -> str:
    return "\\begin{lstlisting}\n" + source + "\n\\end{lstlisting}\n"


def _whole_term_block(title: str, builder: Builder, latex: str | None) -> str:
    node = build(builder)
    runtime, source = specialize(node)
    assert source is not None, "the whole-term examples are all certified to a compiled target"
    rendered = latex if latex is not None else term_to_latex(node)
    note = f"~\\textnormal{{(specialized to {_RUNTIME_LABEL[runtime]})}}"
    heading = f"\\medskip\\noindent\\textbf{{{title}.}}{note}\\quad ${rendered}$\n"
    return heading + _listing(source)


def _cyclic_island_block() -> str:
    """The runnable local specialization: a call-by-value data island in an interpreted cyclic shell."""
    whole = build(_CYCLIC_NINES)
    runtime, _ = specialize(whole)
    assert runtime is Runtime.INTERPRET, "a fold-requiring cyclic term stays interpreted as a whole"
    element = build(app(app(MULT, church(3)), church(3)))
    heading = (
        "\\medskip\\noindent\\textbf{Local specialization in a cyclic term.}"
        "~\\textnormal{(specialized to interpret)}\\quad $Y\\,(\\mathtt{cons}\\,(3 \\times 3))$\n"
    )
    note = (
        "The cyclic stream is fold-requiring, so the whole term stays interpreted; its closed element "
        "$3 \\times 3$ is simply typable, hence a call-by-value island compiled to strict Python:\n"
    )
    result = (
        "The island runs and the interpreter folds around it, so the result is the same finite cyclic "
        "behaviour as pure interpretation, the stream $\\mathtt{cons}\\,9\\,(\\mathtt{cons}\\,9\\,\\cdots)$ "
        "folded to a single cyclic node.\n"
    )
    return heading + note + _listing(codegen(element, Runtime.CALL_BY_VALUE)) + result


_ISLAND_LISTING_MAX_LINE = 200  # the largest combinators compile to multi-thousand-character lines no
# listing can typeset (their deep de Bruijn levels become long unary identifiers); show only the compact
# islands and state the total.


def _compiler_islands_block() -> str:
    """The flagship: the call-by-value islands the specializer finds inside the compiler itself."""
    islands = call_by_value_islands(build(CODEGEN))
    compiled = [(island, codegen(island, Runtime.CALL_BY_VALUE)) for island in islands]
    showable = [
        (island, source)
        for island, source in compiled
        if max((len(line) for line in source.splitlines()), default=0) <= _ISLAND_LISTING_MAX_LINE
    ]
    heading = (
        "\\medskip\\noindent\\textbf{The compiler, specialized: finding call-by-value islands.}\\quad "
        "The compiler is untypable as a whole, since its fixpoint combinator $Y$ self-applies, so it "
        f"stays interpreted; the specializer finds its {len(islands)} maximal closed simply-typable "
        "sub-terms, each a strongly-normalizing combinator compiled to a strict call-by-value island, "
        "while the recursive skeleton is left to the interpreter. The "
        f"{len(showable)} with compact compiled forms are shown (the larger combinators are elided):\n"
    )
    parts = [
        f"\\smallskip\\noindent ${term_to_latex(island)}$\n" + _listing(source)
        for island, source in showable
    ]
    return heading + "\n".join(parts)


def compiler_examples_fragment() -> str:
    """The LaTeX fragment: the specializer's output per term, the islands it finds, and self-hosting."""
    whole_terms = [_whole_term_block(title, builder, latex) for title, builder, latex in _WHOLE_TERM_EXAMPLES]
    bootstrap = (
        "\\medskip\\noindent\\textbf{Self-hosting: the specialized interpret-with-islands form.}\\quad "
        "A term with no whole-graph by-value certificate compiles to interpret-headed Python: it is "
        "reconstructed with the interpreter's node constructors and handed back to the interpreter, with "
        "its closed, shallow, simply-typable sub-terms spliced as compiled by-value islands. The compiler "
        "itself compiles this way; the full self-compiled compilers are committed in the package's "
        "\\texttt{\\_generated\\_stages} directory (one per island depth and Python version; run by the "
        "interpreter on a quoted program, each emits the same Python as the in-process compiler). Here is "
        "a small term in the same form, $\\mathtt{factorial}\\,"
        "(2\\times 3)$, whose multiplication sub-term is spliced as a by-value island:\n"
        + _listing(compile(build(app(FACTORIAL, app(app(MULT, church(2)), church(3))))))
    )
    return (
        _LATEX_HEADER
        + "\n"
        + "\n".join(whole_terms)
        + "\n"
        + _cyclic_island_block()
        + "\n"
        + _compiler_islands_block()
        + "\n"
        + bootstrap
    )
