"""Write the generated compiler-example LaTeX fragment.

The console entry point ``co-lambda-generate-examples`` (see ``pyproject.toml``) runs ``main``;
equivalently ``python -m co_lambda._generate_examples``. The output is committed under
``first-order/generated/`` and ``\\input`` by the paper; a test asserts the committed file matches this
builder, so regenerating after a compiler change is mandatory (and idempotent otherwise). The
self-compiled compilers are the staged compilers under ``_generated_stages/`` in this package,
regenerated by ``co-lambda-benchmark`` (``co_lambda._benchmark``).
"""

from __future__ import annotations

from pathlib import Path

from co_lambda._generate import compiler_examples_fragment

# src/co_lambda/_generate_examples.py -> repo root is four parents up.
_REPO_ROOT = Path(__file__).resolve().parents[4]
_LATEX_OUTPUT = _REPO_ROOT / "first-order" / "generated" / "compiler-examples.tex"


def main() -> None:
    _LATEX_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _LATEX_OUTPUT.write_text(compiler_examples_fragment())
    print(f"wrote {_LATEX_OUTPUT}")


if __name__ == "__main__":
    main()
